### ISSUE TITLE
module aci_epg  cannot add several contract_consumed to epg

### ISSUE THREAD

**Issue by sorpa** [jedelman8/aci-ansible#2]
Hi,

Thank you for your nice ACI modules. I have create playbook which creates nicely almost everything...except several consumed_contracts. I have tried several ways without success. Might be problem with aci_epg module?  Everything works fine if I give just one consumed contract but with two it gives it below:

failed: [172.31.30.44](item={u'epgname': u'epg2', u'contract_consumed': [u'contract1', u'humppa3'], u'anpname': u'anp2', u'contract_provided': u'contract2'}) => {"contract": "['contract1', 'humppa3']", "failed": true, "invocation": {"module_args": {"anp": "anp2", "bridge_domain": "pasitestBD", "consumed_contracts": "['contract1', 'humppa3']", "descr": null, "host": "172.31.30.44", "name": "epg2", "password": "Syksy2016!", "prio": null, "protocol": "https", "provided_contracts": "contract2", "state": "present", "tenant": "pasitenant", "username": "sorpa", "vmm_domain": "vcenter"}, "module_name": "aci_epg"}, "item": {"anpname": "anp2", "contract_consumed": ["contract1", "humppa3"], "contract_provided": "contract2", "epgname": "epg2"}, "msg": "contract does not exist"}

Also I tried to add with first run playbook with one consumed_contract and then next round add new one, but it just updates the current consumed contract under EPG-> to new contractname., so not adding second line. Playbook below :-) Any hints appreciated.

Br,Pasi
---
- hosts: apic 
  gather_facts: false
  connection: local
  user: remote
  sudo: true
# vars_files:
# \- /etc/ansible/host_vars/apic

  vars:
    apic_username: 'huuhaa'
    apic_password: 'allright'
    apic_host: 'XX.XX.XX.XX'
    list_dict:
      - {anpname: "anp1", epgname: "epg1", contract_provided: "contract1", contract_consumed: "contract2"}
      - {anpname: "anp2", epgname: "epg2", contract_provided: "contract2", contract_consumed: ["contract1", "humppa3"]}
      - {anpname: "anp3", epgname: "epg3", contract_provided: "contract3", contract_consumed: "contract2"}
    list_dict2:
      - {contractname: "contract1", scope: "tenant", subjectname: "subject1"}
      - {contractname: "contract2", scope: "tenant", subjectname: "subject2"}
      - {contractname: "contract3", scope: "tenant", subjectname: "subject3"}
      - {contractname: "humppa3", scope: "tenant", subjectname: "humppa3"}

  tasks:
    - aci_tenant:
        name: pasitenant
        state: present
        host: "{{ apic_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"

```
- aci_contract: 
    name: "{{item.contractname}}" 
    descr: 'Testicontracteja' 
    tenant: pasitenant
    scope: "{{item.scope}}" 
    state: present
    host: "{{ apic_host }}"
    username: "{{ apic_username }}"
    password: "{{ apic_password }}"
  with_items: "{{ list_dict2 }}"

- aci_contract_subject: 
    name: "{{item.subjectname}}" 
    contract: "{{item.contractname}}"
   #filters: Web_Filter 
    tenant: pasitenant 
    host: "{{ apic_host }}"
    username: "{{ apic_username }}"
    password: "{{ apic_password }}" 
  with_items: "{{ list_dict2 }}"

- aci_anp: 
    name: "{{ item.anpname }}"
    tenant: pasitenant
    state: present 
    host: "{{ apic_host }}"
    username: "{{ apic_username }}"
    password: "{{ apic_password }}" 
  with_items: "{{ list_dict }}"

- aci_context: 
    name: pasitestVRF 
    descr: 'Pasin testi voi poistaa' 
    tenant: pasitenant 
    state: present 
    host: "{{ apic_host }}" 
    username: "{{ apic_username }}" 
    password: "{{apic_password}}"

- aci_bridge_domain: 
    name: pasitestBD 
    context: pasitestVRF 
    subnet: 10.10.10.1/24 
    tenant: pasitenant 
    state: present 
    host: "{{ apic_host }}" 
    username: "{{ apic_username }}" 
    password: "{{ apic_password }}"
```

   #This loop creates the EPGses and the contracts provided and consumed 
    - aci_epg:
        name: "{{item.epgname}}" 
        consumed_contracts: "{{item.contract_consumed}}" 
        provided_contracts: "{{item.contract_provided}}" 
        bridge_domain: pasitestBD 
        anp: "{{item.anpname}}" 
        tenant: pasitenant 
        vmm_domain: vcenter 
        state: present 
        host: "{{ apic_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
      with_items: "{{ list_dict }}"
